#image: hpccsystems/platform

image:
  file: .gitpod.Dockerfile

ports:
  - port: 22
    onOpen: ignore
    visibility: public
  - port: 8010
    onOpen: ignore
    visibility: public
  - port: 8002
    onOpen: ignore
    visibility: public
  - port: 7601
    onOpen: ignore
  - port: 7100
    onOpen: ignore
  - port: 7070
    onOpen: ignore
  - port: 8510
    onOpen: ignore
  - port: 9876
    onOpen: ignore
  - port: 8877
    onOpen: ignore
  - port: 20000
    onOpen: ignore
  - port: 20002
    onOpen: ignore
  - port: 20100
    onOpen: ignore
  - port: 9004
    onOpen: ignore

vscode:
  extensions:
    - https://github.com/hpcc-systems/vscode-ecl/releases/latest/download/hpcc-systems.ecl.vsix
    - https://github.com/GordonSmith/vscode-ojs/releases/latest/download/gordonsmith.observable-js.vsix

tasks:
  - name: Start HPCC-Systems Platform
    command: sudo /etc/init.d/hpcc-init start



